### test index

GET http://localhost:8080/Cargo.toml

### test static file with tower-http

GET  http://localhost:8080/static/README.md
Range: bytes=0-100


### test dir
GET  http://localhost:8080/static/lib.rs
